/**
 * _data.js — Internal product database
 * এটা তোমার actual database/ORM দিয়ে replace করবে।
 * এখন সব in-memory dummy data।
 */

export const PRODUCTS = [
  {
    id: 1,
    title: "iPhone 15 Pro Max",
    description: "Apple iPhone 15 Pro Max — latest model with titanium design and A17 Pro chip.",
    price: 1199,
    salePrice: null,
    discountPercentage: 0,
    rating: 4.8,
    stock: 42,
    brand: "Apple",
    category: "smartphones",
    collection: ["new-arrivals", "featured"],
    badge: "NEW",
    tags: ["apple", "iphone", "5g"],
    thumbnail: "https://cdn.dummyjson.com/product-images/1/thumbnail.jpg",
    images: [
      "https://cdn.dummyjson.com/product-images/1/1.jpg",
      "https://cdn.dummyjson.com/product-images/1/2.jpg",
    ],
  },
  {
    id: 2,
    title: "Samsung Galaxy S24 Ultra",
    description: "Samsung Galaxy S24 Ultra with 200MP camera and built-in S Pen.",
    price: 1099,
    salePrice: 949,
    discountPercentage: 14,
    rating: 4.7,
    stock: 28,
    brand: "Samsung",
    category: "smartphones",
    collection: ["featured", "best-sellers"],
    badge: "SALE",
    tags: ["samsung", "android", "5g"],
    thumbnail: "https://cdn.dummyjson.com/product-images/2/thumbnail.jpg",
    images: ["https://cdn.dummyjson.com/product-images/2/1.jpg"],
  },
  {
    id: 3,
    title: "MacBook Air M3",
    description: "Thin, light, and with Apple M3 chip — incredible all-day battery life.",
    price: 1299,
    salePrice: 1099,
    discountPercentage: 15,
    rating: 4.9,
    stock: 15,
    brand: "Apple",
    category: "laptops",
    collection: ["featured", "new-arrivals"],
    badge: "HOT",
    tags: ["apple", "laptop", "m3"],
    thumbnail: "https://cdn.dummyjson.com/product-images/6/thumbnail.jpg",
    images: ["https://cdn.dummyjson.com/product-images/6/1.jpg"],
  },
  {
    id: 4,
    title: "Sony WH-1000XM5",
    description: "Industry-leading noise canceling wireless headphones.",
    price: 349,
    salePrice: 279,
    discountPercentage: 20,
    rating: 4.8,
    stock: 67,
    brand: "Sony",
    category: "headphones",
    collection: ["best-sellers", "flash-sale"],
    badge: "20% OFF",
    tags: ["sony", "headphones", "noise-canceling"],
    thumbnail: "https://cdn.dummyjson.com/product-images/22/thumbnail.jpg",
    images: ["https://cdn.dummyjson.com/product-images/22/1.jpg"],
  },
  {
    id: 5,
    title: "Nike Air Max 270",
    description: "Nike Air Max 270 sneakers — max comfort for all-day wear.",
    price: 150,
    salePrice: 119,
    discountPercentage: 21,
    rating: 4.5,
    stock: 120,
    brand: "Nike",
    category: "shoes",
    collection: ["best-sellers"],
    badge: "POPULAR",
    tags: ["nike", "sneakers", "running"],
    thumbnail: "https://cdn.dummyjson.com/product-images/48/thumbnail.jpg",
    images: ["https://cdn.dummyjson.com/product-images/48/1.jpg"],
  },
  {
    id: 6,
    title: "Dell XPS 15",
    description: "Dell XPS 15 with OLED display and Intel Core i9 processor.",
    price: 1799,
    salePrice: null,
    discountPercentage: 0,
    rating: 4.6,
    stock: 9,
    brand: "Dell",
    category: "laptops",
    collection: ["featured"],
    badge: null,
    tags: ["dell", "laptop", "oled"],
    thumbnail: "https://cdn.dummyjson.com/product-images/7/thumbnail.jpg",
    images: ["https://cdn.dummyjson.com/product-images/7/1.jpg"],
  },
  {
    id: 7,
    title: "Apple Watch Series 9",
    description: "Apple Watch Series 9 with double tap gesture and brighter display.",
    price: 399,
    salePrice: 349,
    discountPercentage: 13,
    rating: 4.7,
    stock: 55,
    brand: "Apple",
    category: "watches",
    collection: ["new-arrivals", "featured"],
    badge: "NEW",
    tags: ["apple", "smartwatch", "health"],
    thumbnail: "https://cdn.dummyjson.com/product-images/63/thumbnail.jpg",
    images: ["https://cdn.dummyjson.com/product-images/63/1.jpg"],
  },
  {
    id: 8,
    title: "iPad Pro 12.9\"",
    description: "iPad Pro with M2 chip, Liquid Retina XDR display and ProMotion technology.",
    price: 1099,
    salePrice: null,
    discountPercentage: 0,
    rating: 4.8,
    stock: 31,
    brand: "Apple",
    category: "tablets",
    collection: ["featured", "best-sellers"],
    badge: null,
    tags: ["apple", "ipad", "tablet"],
    thumbnail: "https://cdn.dummyjson.com/product-images/24/thumbnail.jpg",
    images: ["https://cdn.dummyjson.com/product-images/24/1.jpg"],
  },
  {
    id: 9,
    title: "Adidas Ultraboost 23",
    description: "Adidas Ultraboost 23 running shoes with Boost midsole technology.",
    price: 180,
    salePrice: 139,
    discountPercentage: 23,
    rating: 4.6,
    stock: 88,
    brand: "Adidas",
    category: "shoes",
    collection: ["flash-sale", "best-sellers"],
    badge: "SALE",
    tags: ["adidas", "running", "boost"],
    thumbnail: "https://cdn.dummyjson.com/product-images/49/thumbnail.jpg",
    images: ["https://cdn.dummyjson.com/product-images/49/1.jpg"],
  },
  {
    id: 10,
    title: "Samsung 55\" QLED 4K TV",
    description: "Samsung 55 inch QLED 4K Smart TV with Quantum HDR and Alexa built-in.",
    price: 799,
    salePrice: 649,
    discountPercentage: 19,
    rating: 4.5,
    stock: 22,
    brand: "Samsung",
    category: "televisions",
    collection: ["flash-sale"],
    badge: "HOT DEAL",
    tags: ["samsung", "tv", "4k", "smart-tv"],
    thumbnail: "https://cdn.dummyjson.com/product-images/14/thumbnail.jpg",
    images: ["https://cdn.dummyjson.com/product-images/14/1.jpg"],
  },
  {
    id: 11,
    title: "Bose QuietComfort 45",
    description: "Bose QC45 wireless headphones — legendary comfort and quiet.",
    price: 279,
    salePrice: 229,
    discountPercentage: 18,
    rating: 4.6,
    stock: 44,
    brand: "Bose",
    category: "headphones",
    collection: ["best-sellers"],
    badge: "18% OFF",
    tags: ["bose", "headphones", "wireless"],
    thumbnail: "https://cdn.dummyjson.com/product-images/23/thumbnail.jpg",
    images: ["https://cdn.dummyjson.com/product-images/23/1.jpg"],
  },
  {
    id: 12,
    title: "Google Pixel 8 Pro",
    description: "Google Pixel 8 Pro with Tensor G3 chip and advanced AI features.",
    price: 999,
    salePrice: 849,
    discountPercentage: 15,
    rating: 4.6,
    stock: 37,
    brand: "Google",
    category: "smartphones",
    collection: ["new-arrivals"],
    badge: "NEW",
    tags: ["google", "pixel", "android", "ai"],
    thumbnail: "https://cdn.dummyjson.com/product-images/3/thumbnail.jpg",
    images: ["https://cdn.dummyjson.com/product-images/3/1.jpg"],
  },
  {
    id: 13,
    title: "Canon EOS R50",
    description: "Canon EOS R50 mirrorless camera — perfect for content creators.",
    price: 679,
    salePrice: null,
    discountPercentage: 0,
    rating: 4.7,
    stock: 18,
    brand: "Canon",
    category: "cameras",
    collection: ["featured", "new-arrivals"],
    badge: null,
    tags: ["canon", "camera", "mirrorless"],
    thumbnail: "https://cdn.dummyjson.com/product-images/80/thumbnail.jpg",
    images: ["https://cdn.dummyjson.com/product-images/80/1.jpg"],
  },
  {
    id: 14,
    title: "Levi's 511 Slim Jeans",
    description: "Levi's 511 slim fit jeans — classic American style in stretch denim.",
    price: 79,
    salePrice: 59,
    discountPercentage: 25,
    rating: 4.4,
    stock: 200,
    brand: "Levi's",
    category: "clothing",
    collection: ["flash-sale", "best-sellers"],
    badge: "25% OFF",
    tags: ["levis", "jeans", "denim"],
    thumbnail: "https://cdn.dummyjson.com/product-images/52/thumbnail.jpg",
    images: ["https://cdn.dummyjson.com/product-images/52/1.jpg"],
  },
  {
    id: 15,
    title: "PlayStation 5 Console",
    description: "Sony PlayStation 5 Digital Edition — experience lightning-fast loading.",
    price: 449,
    salePrice: null,
    discountPercentage: 0,
    rating: 4.9,
    stock: 5,
    brand: "Sony",
    category: "gaming",
    collection: ["featured", "best-sellers"],
    badge: "LIMITED",
    tags: ["sony", "ps5", "gaming", "console"],
    thumbnail: "https://cdn.dummyjson.com/product-images/67/thumbnail.jpg",
    images: ["https://cdn.dummyjson.com/product-images/67/1.jpg"],
  },
  {
    id: 16,
    title: "Dyson V15 Detect",
    description: "Dyson V15 Detect cordless vacuum with laser dust detection.",
    price: 749,
    salePrice: 599,
    discountPercentage: 20,
    rating: 4.7,
    stock: 26,
    brand: "Dyson",
    category: "home-appliances",
    collection: ["featured"],
    badge: "SALE",
    tags: ["dyson", "vacuum", "cordless"],
    thumbnail: "https://cdn.dummyjson.com/product-images/9/thumbnail.jpg",
    images: ["https://cdn.dummyjson.com/product-images/9/1.jpg"],
  },
  {
    id: 17,
    title: "AirPods Pro (2nd gen)",
    description: "Apple AirPods Pro 2nd generation with Adaptive Audio and USB-C.",
    price: 249,
    salePrice: 189,
    discountPercentage: 24,
    rating: 4.8,
    stock: 93,
    brand: "Apple",
    category: "headphones",
    collection: ["best-sellers", "flash-sale"],
    badge: "24% OFF",
    tags: ["apple", "airpods", "wireless", "anc"],
    thumbnail: "https://cdn.dummyjson.com/product-images/21/thumbnail.jpg",
    images: ["https://cdn.dummyjson.com/product-images/21/1.jpg"],
  },
  {
    id: 18,
    title: "LG OLED 65\" evo C3",
    description: "LG OLED evo C3 65 inch 4K Smart TV — perfect blacks and vivid colors.",
    price: 1499,
    salePrice: 1199,
    discountPercentage: 20,
    rating: 4.8,
    stock: 11,
    brand: "LG",
    category: "televisions",
    collection: ["featured", "flash-sale"],
    badge: "HOT",
    tags: ["lg", "oled", "4k", "tv"],
    thumbnail: "https://cdn.dummyjson.com/product-images/15/thumbnail.jpg",
    images: ["https://cdn.dummyjson.com/product-images/15/1.jpg"],
  },
  {
    id: 19,
    title: "Nike Dri-FIT T-Shirt",
    description: "Nike Dri-FIT moisture-wicking performance t-shirt for training.",
    price: 35,
    salePrice: 25,
    discountPercentage: 29,
    rating: 4.5,
    stock: 350,
    brand: "Nike",
    category: "clothing",
    collection: ["best-sellers", "flash-sale"],
    badge: "29% OFF",
    tags: ["nike", "tshirt", "sport", "dri-fit"],
    thumbnail: "https://cdn.dummyjson.com/product-images/55/thumbnail.jpg",
    images: ["https://cdn.dummyjson.com/product-images/55/1.jpg"],
  },
  {
    id: 20,
    title: "Kindle Paperwhite 11th Gen",
    description: "Amazon Kindle Paperwhite — 6.8 inch display with adjustable warm light.",
    price: 139,
    salePrice: 99,
    discountPercentage: 29,
    rating: 4.7,
    stock: 180,
    brand: "Amazon",
    category: "tablets",
    collection: ["best-sellers", "flash-sale"],
    badge: "SALE",
    tags: ["amazon", "kindle", "ereader"],
    thumbnail: "https://cdn.dummyjson.com/product-images/25/thumbnail.jpg",
    images: ["https://cdn.dummyjson.com/product-images/25/1.jpg"],
  },
];

// Collections definition
export const COLLECTIONS = {
  'featured':     { name: 'Featured',      productIds: [1, 2, 3, 6, 7, 8, 13, 15, 16, 18] },
  'new-arrivals': { name: 'New Arrivals',  productIds: [1, 3, 7, 12, 13] },
  'best-sellers': { name: 'Best Sellers',  productIds: [2, 4, 5, 8, 9, 11, 14, 15, 17, 19, 20] },
  'flash-sale':   { name: 'Flash Sale',    productIds: [4, 9, 10, 14, 17, 18, 19, 20] },
};

// Helper — filter + limit + search
export function queryProducts({ category, ids, search, collection, limit = 20, skip = 0 }) {
  let results = [...PRODUCTS];

  if (ids?.length) {
    results = results.filter(p => ids.map(String).includes(String(p.id)));
  }
  if (category) {
    results = results.filter(p => p.category === category);
  }
  if (collection) {
    const col = COLLECTIONS[collection];
    if (col) results = results.filter(p => col.productIds.includes(p.id));
  }
  if (search) {
    const q = search.toLowerCase();
    results = results.filter(p =>
      p.title.toLowerCase().includes(q) ||
      p.description.toLowerCase().includes(q) ||
      p.category.toLowerCase().includes(q) ||
      p.brand.toLowerCase().includes(q) ||
      p.tags.some(t => t.includes(q))
    );
  }

  const total = results.length;
  return {
    products: results.slice(skip, skip + limit),
    total,
    skip,
    limit,
  };
}
